spring:
  messages:
    basename: static/localFile/text
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 1000MB
  datasource:
    druid:
      default-auto-commit: false
      initial-size: 3
      max-active: 10
      max-wait: 30000
      min-idle: 5
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 123456
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 3000
          merge-sql: true
        slf4j:
          enabled: true
      filters: stat,slf4j
      validation-query: select 1 from DUAL
    password: tongyi0923
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/teacherselect?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    password: redispw
    port: 6379
    database: 0
    timeout: 300000
    lettuce:
      pool:
        enabled: true
        max-active: -1
        max-idle: 100
        min-idle: 50
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: tongyi0923
#actable:
#  table:
#   auto: add
#  model:
#    pack: tbs
#  database:
#   type: mysql

logging:
  file:
    path: /Users/abstergo/Downloads/log
  level:
    sql: error
    tbs: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      table-underline: false
  mapper-locations: classpath*:mapper/*/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 500
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: xiaoymin@foxmail.com
    concat: 八一菜刀
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - tbs.newgenteacherselect.controller
tbs:
  framework:
    async:
      locker: REDIS_LOCKER
      result-holder: tbs.framework.redis.impl.RedisAsyncResultHolder
    controller:
      access-element: tbs.newgenteacherselect.config.impl.AccessManager
      access-inputer: tbs.newgenteacherselect.config.impl.CookiesAccessInputer
