spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 1000MB
  datasource:
    druid:
      default-auto-commit: false
      initial-size: 20
      max-active: 100
      min-idle: 10
    password: tongyi0923
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/teacherselect?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    password: redispw
    port: 6379
    database: 0
    timeout: 300000
    lettuce:
      pool:
        enabled: true
        max-active: -1
        max-idle: 100
        min-idle: 50
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: tongyi0923
tbs:
  thread:
    locker:
      redis:
        enable: true
        timeout: 60